image: ghcr.io/mass4org/fanstatic:alpine

variables:
  GIT_SUBMODULE_STRATEGY: normal
  GIT_SUBMODULE_UPDATE_FLAGS: --remote

stages:
  - build
  - pages

build:
  stage: build
  script:
    - fanstatic --version
    - fanstatic

pages:
  stage: pages
  script:
    - fanstatic
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
